# Generated by Django 3.2.14 on 2022-07-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stocksinfo_stock_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksinfo',
            options={},
        ),
    ]
